kernel:
    resource: ../src/Kernel.php
    type: annotation

api_fruits:
    type: attribute
    resource: ../src/Controller/FruitController.php
    prefix: api/v1/fruits

api_vegetables:
    type: attribute
    resource: ../src/Controller/VegetableController.php
    prefix: api/v1/vegetables
